# Site settings
title: heap.ch
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://heap.ch" # the base hostname & protocol for your site
twitter_username: stepmuel
github_username:  stepmuel
highlighter: pygments

permalink: /blog/:categories/:year/:month/:day/:title/

# Build settings
markdown: kramdown
